version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - TYPEFORM_WEBHOOK_SECRET=${TYPEFORM_WEBHOOK_SECRET}
  frontend:
    build: ./frontend
    expose:
      - "3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/etc/nginx/certificates
    depends_on:
      - frontend
      - backend