version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    expose:
      - "5000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/etc/nginx/certificates
    depends_on:
      - frontend
      - backend
